name: Staging Merge
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check staging merge
      run: |
        cd ${GITHUB_WORKSPACE}
        git branch -a
        echo ... git merge-base remotes/origin/staging $GITHUB_REF ...
        MERGE_BASE=$(git merge-base remotes/origin/staging remotes/origin/${GITHUB_REF##*/})
        if [[ $MERGE_BASE = $GITHUB_SHA ]]; then
          export DESCRIPTION=$GITHUB_REF is merged into staging;
          export STATE=success;
          echo "{\"state\":\"$STATE\",\"description\":\"$DESCRIPTION\",\"context\":\"checks.staging_merge\"}"
          return 0
        else
          export DESCRIPTION=$GITHUB_REF is not merged into staging;
          export STATE=pending;
          echo "{\"state\":\"$STATE\",\"description\":\"$DESCRIPTION\",\"context\":\"checks.staging_merge\"}"
          return 128
        fi
        #curl --request POST \
        #  --url https://api.github.com/repos/${{ github.repository }}/statuses/$GITHUB_SHA \
        #  --header "authorization: Bearer $GITHUB_TOKEN" \
        #  --header 'content-type: application/json' \
        #  --data "{\"state\":\"$STATE\",\"description\":\"$DESCRIPTION\",\"context\":\"checks.staging_merge\"}"
