name: Staging Merge
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check staging merge
      run: |
        cd ${GITHUB_WORKSPACE}
        git checkout staging
        MERGE_DESTINATION_BRANCH=staging
        MERGE_SOURCE_BRANCH=$(git rev-parse --abbrev-ref $GITHUB_SHA)
        echo ... git rev-parse --abbrev-ref $GITHUB_SHA ...
        echo ... $(git rev-parse --abbrev-ref $GITHUB_SHA) ...
        echo ... git merge-base $MERGE_DESTINATION_BRANCH $MERGE_SOURCE_BRANCH ...
        MERGE_BASE=$(git merge-base $MERGE_DESTINATION_BRANCH $MERGE_SOURCE_BRANCH)
        if [[ $MERGE_BASE = $GITHUB_SHA ]]; then
          DESCRIPTION=$MERGE_SOURCE_BRANCH is merged into $MERGE_DESTINATION_BRANCH;
          STATE=success;
        else
          DESCRIPTION=$MERGE_SOURCE_BRANCH is not merged into $MERGE_DESTINATION_BRANCH;
          STATE=pending;
        fi
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/$GITHUB_SHA \
          --header "authorization: Bearer $GITHUB_TOKEN" \
          --header 'content-type: application/json' \
          --data "{\"state\":\"$STATE\",\"description\":\"$DESCRIPTION\",\"context\":\"checks.staging_merge\"}"
