name: Staging Merge
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check staging merge
      run: |
        cd ${GITHUB_WORKSPACE}
        export
        MERGE_DESTINATION_BRANCH=staging
        echo ... git merge-base $MERGE_DESTINATION_BRANCH $GITHUB_REF ...
        MERGE_BASE=$(git merge-base $MERGE_DESTINATION_BRANCH $GITHUB_REF)
        if [[ $MERGE_BASE = $GITHUB_SHA ]]; then
          DESCRIPTION=$GITHUB_REF is merged into $MERGE_DESTINATION_BRANCH;
          STATE=success;
        else
          DESCRIPTION=$GITHUB_REF is not merged into $MERGE_DESTINATION_BRANCH;
          STATE=pending;
        fi
        echo "{\"state\":\"$STATE\",\"description\":\"$DESCRIPTION\",\"context\":\"checks.staging_merge\"}"
        #curl --request POST \
        #  --url https://api.github.com/repos/${{ github.repository }}/statuses/$GITHUB_SHA \
        #  --header "authorization: Bearer $GITHUB_TOKEN" \
        #  --header 'content-type: application/json' \
        #  --data "{\"state\":\"$STATE\",\"description\":\"$DESCRIPTION\",\"context\":\"checks.staging_merge\"}"
